# Generated by Django 5.2.1 on 2026-06-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
