# Generated by Django 5.2.1 on 2026-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_faq_testimonial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_active', 'order'], name='cms_faq_is_acti_d9478f_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_active'], name='cms_testimo_is_acti_4e9832_idx'),
        ),
    ]
