# Generated by Django 5.2.1 on 2026-06-06 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_courses_cou_is_acti_8e0d16_idx_and_more'),
        ('enrollments', '0002_enrollment_enrollments_student_885f1d_idx_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'status'], name='payments_pa_student_2663d2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-submitted_at'], name='payments_pa_submitt_5d3704_idx'),
        ),
    ]
